#!/usr/bin/env bash

# Ensure config files mounted as bind-mount *files* exist before compose runs.
# Docker creates a directory when the host path is missing, which breaks the
# container with "not a directory" errors.
ensure_default_configs() {
  local defaults="$REPO_DIR/docker/config"

  mkdir -p "$INSTALL_DIR/config/mqtt"
  mkdir -p "$INSTALL_DIR/config/mowgli"
  mkdir -p "$INSTALL_DIR/config/om"
  mkdir -p "$INSTALL_DIR/config/db"

  if [ ! -f "$INSTALL_DIR/config/mqtt/mosquitto.conf" ]; then
    cp "$defaults/mqtt/mosquitto.conf" "$INSTALL_DIR/config/mqtt/mosquitto.conf"
    info "Created default mosquitto.conf"
  fi

  if [ ! -f "$INSTALL_DIR/config/cyclonedds.xml" ]; then
    cp "$defaults/cyclonedds.xml" "$INSTALL_DIR/config/cyclonedds.xml"
    info "Created default cyclonedds.xml"
  fi
}

build_compose_stack() {
  COMPOSE_FILES=()

  COMPOSE_FILES+=("compose/docker-compose.base.yml")
  COMPOSE_FILES+=("compose/docker-compose.gui.yml")
  COMPOSE_FILES+=("compose/docker-compose.mqtt.yml")
  COMPOSE_FILES+=("compose/docker-compose.gps.yml")

  # Foxglove bridge is controlled via the ENABLE_FOXGLOVE env var passed
  # to the ROS2 container (see docker-compose.base.yml).  No separate
  # compose file is needed — the launch file starts/skips the node.

  if [[ "${LIDAR_ENABLED:-true}" == "true" && "${LIDAR_TYPE:-none}" != "none" ]]; then
    case "${LIDAR_TYPE:-}" in
      rplidar)
        # RPLiDAR A-series: supported, but A1 only is the tested combo today.
        # A2 / A3 / S-series images are built but untested — please report back.
        COMPOSE_FILES+=("compose/docker-compose.lidar-rplidar.yml")
        ;;
      ldlidar)
        COMPOSE_FILES+=("compose/docker-compose.lidar-ldlidar.yml")
        ;;
      stl27l)
        warn "LIDAR_TYPE=stl27l is EXPERIMENTAL — driver is a stub, motion tests not run yet."
        COMPOSE_FILES+=("compose/docker-compose.lidar-stl27l.yml")
        ;;
      *)
        warn "Unknown LIDAR_TYPE: ${LIDAR_TYPE:-unset}"
        ;;
    esac
  fi

  if [[ "${TFLUNA_FRONT_ENABLED:-false}" == "true" ]]; then
    warn "TF-Luna (front) integration is EXPERIMENTAL and not wired into collision_monitor yet."
    COMPOSE_FILES+=("compose/docker-compose.tfluna-front.yml")
  fi

  if [[ "${TFLUNA_EDGE_ENABLED:-false}" == "true" ]]; then
    warn "TF-Luna (edge) integration is EXPERIMENTAL and not wired into collision_monitor yet."
    COMPOSE_FILES+=("compose/docker-compose.tfluna-edge.yml")
  fi

  if [[ "${ENABLE_MAVROS:-false}" == "true" ]]; then
    warn "MAVROS bridge is COMING SOON — enabling this starts the service but nothing in Mowgli consumes it."
    COMPOSE_FILES+=("compose/docker-compose.mavros.yml")
  fi

  if [[ "${ENABLE_VESC:-false}" == "true" ]]; then
    warn "VESC motor-controller support is COMING SOON — not integrated with the STM32-based hardware_bridge flow yet."
    COMPOSE_FILES+=("compose/docker-compose.vesc.yml")
  fi

  info "Compose stack:"
  for f in "${COMPOSE_FILES[@]}"; do
    echo "  - $f"
  done
}

# Extract service definitions from a compose template file.
# Outputs everything between the "services:" line and the next top-level key
# (or EOF), preserving indentation. Skips x-ros2-env anchors since the merged
# file defines its own single anchor.
_extract_services() {
  awk '/^services:/{found=1; next} /^[^ #]/{if(found) exit} found{print}' "$1"
}

write_compose_merged() {
  # Generate a single self-contained docker-compose.yaml by merging all
  # selected compose templates. Users get one readable file instead of
  # needing to understand Docker Compose include/project mechanics.
  local output="$INSTALL_DIR/docker-compose.yaml"

  {
    cat <<'HEADER'
# Auto-generated by mowglinext installer — do not edit manually
# Re-run the installer to regenerate after changing hardware config

x-ros2-env: &ros2-env
  ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
  RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
  CYCLONEDDS_URI: file:///cyclonedds.xml
  ROS_AUTOMATIC_DISCOVERY_RANGE: LOCALHOST
  RCUTILS_COLORIZED_OUTPUT: "1"
  RCUTILS_LOGGING_USE_STDOUT: "1"
  LIDAR_ENABLED: ${LIDAR_ENABLED:-true}
  ENABLE_FOXGLOVE: ${ENABLE_FOXGLOVE:-true}

services:
HEADER

    for f in "${COMPOSE_FILES[@]}"; do
      _extract_services "$INSTALL_DIR/$f"
      echo ""
    done

    echo "volumes:"
    echo "  mowgli_maps:"
  } > "$output"

  info "Wrote $output"
}

run_compose_stack() {
  cd "$INSTALL_DIR" || return 1

  ensure_default_configs

  echo ""
  info "Selected services:"
  for f in "${COMPOSE_FILES[@]}"; do
    echo "  - $f"
  done
  echo ""

  write_compose_merged

  info "Using env file: $INSTALL_DIR/.env"

  info "Pulling selected images..."
  docker compose --env-file "$INSTALL_DIR/.env" pull

  echo ""
  info "Starting stack..."
  docker compose --env-file "$INSTALL_DIR/.env" up -d

  echo ""
  info "Current containers:"
  docker compose --env-file "$INSTALL_DIR/.env" ps
}