coverage_planner_node:
  ros__parameters:
    tool_width: 0.18
    headland_passes: 1
    headland_width: 0.18
    default_mow_angle: -1.0
    path_spacing: 0.5
    min_turning_radius: 0.3
    map_frame: "map"
