rosbridge_websocket:
  ros__parameters:
    port: 9090
    address: ""
    max_message_size: 10000000
    authenticate: false
    # Topics to expose (empty = all)
    topics_glob: []
    services_glob: []
    params_glob: []
