services:
  gnss_unicore:
    container_name: gnss_unicore
    image: ${MOWGLI_ROS2_IMAGE}

    network_mode: host
    ipc: host

    devices:
      - ${GPS_UART_DEVICE:-/dev/ttyUSB0}:${GPS_PORT:-/dev/gps}

    volumes:
      - ./config/mowgli:/config/mowgli

    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp

    command: >
      ros2 run mowgli_unicore_gnss um982_node
      --ros-args
      --params-file /config/mowgli/gnss_unicore.yaml
      --ros-args
      -p port:=${GPS_PORT:-/dev/gps}
      -p baudrate:=${GPS_BAUD:-921600}

    restart: unless-stopped