services:
  gnss_unicore:
    container_name: gnss_unicore
    image: ${MOWGLI_ROS2_IMAGE}

    network_mode: host
    ipc: host

    devices:
      - ${GPS_UART_DEVICE:-/dev/ttyUSB0}:${GPS_PORT:-/dev/gps}

    volumes:
      - ./docker/config/mowgli:/config/mowgli:ro
      - ./docker/config/cyclonedds.xml:/cyclonedds.xml:ro

    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp

    command: >
      ros2 launch mowgli_bringup unicore_gnss.launch.py
      unicore_serial_port:=${GPS_PORT:-/dev/gps}
      unicore_baudrate:=${GPS_BAUD:-921600}

    restart: unless-stopped
