// Code generated by generate_go_msgs.sh — DO NOT EDIT.
package mowgli

import (
	"github.com/cedbossneo/mowglinext/pkg/msgs/geometry"
	"github.com/cedbossneo/mowglinext/pkg/msgs/nav"
)

// AddMowingAreaReq for mowgli_interfaces/srv/AddMowingArea request.
type AddMowingAreaReq struct {
	Area                      MapArea                        `json:"area"`
	IsNavigationArea          bool                           `json:"is_navigation_area"`
}

// AddMowingAreaRes for mowgli_interfaces/srv/AddMowingArea response.
type AddMowingAreaRes struct {
	Success                   bool                           `json:"success"`
}

// AreaRecordingReq for mowgli_interfaces/srv/AreaRecording request.
type AreaRecordingReq struct {
	Command                   uint8                          `json:"command"`
	AreaName                  string                         `json:"area_name"`
	IsExclusionZone           bool                           `json:"is_exclusion_zone"`
}

// AreaRecordingRes for mowgli_interfaces/srv/AreaRecording response.
type AreaRecordingRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	Polygon                   geometry.Polygon               `json:"polygon"`
}

// CalibrateImuYawReq for mowgli_interfaces/srv/CalibrateImuYaw request.
type CalibrateImuYawReq struct {
	DurationSec               float64                        `json:"duration_sec"`
}

// CalibrateImuYawRes for mowgli_interfaces/srv/CalibrateImuYaw response.
type CalibrateImuYawRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
	ImuYawRad                 float64                        `json:"imu_yaw_rad"`
	ImuYawDeg                 float64                        `json:"imu_yaw_deg"`
	SamplesUsed               int32                          `json:"samples_used"`
	StdDevDeg                 float64                        `json:"std_dev_deg"`
}

// ClearMapReq for mowgli_interfaces/srv/ClearMap request (empty).
type ClearMapReq struct{}

// ClearMapRes for mowgli_interfaces/srv/ClearMap response.
type ClearMapRes struct {
	Success                   bool                           `json:"success"`
}

// ClearObstacleReq for mowgli_interfaces/srv/ClearObstacle request.
type ClearObstacleReq struct {
	ObstacleId                uint32                         `json:"obstacle_id"`
}

// ClearObstacleRes for mowgli_interfaces/srv/ClearObstacle response.
type ClearObstacleRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

// EmergencyStopReq for mowgli_interfaces/srv/EmergencyStop request.
type EmergencyStopReq struct {
	Emergency                 uint8                          `json:"emergency"`
}

// EmergencyStopRes for mowgli_interfaces/srv/EmergencyStop response.
type EmergencyStopRes struct {
	Success                   bool                           `json:"success"`
}

// GetCoverageStatusReq for mowgli_interfaces/srv/GetCoverageStatus request.
type GetCoverageStatusReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
}

// GetCoverageStatusRes for mowgli_interfaces/srv/GetCoverageStatus response.
type GetCoverageStatusRes struct {
	Success                   bool                           `json:"success"`
	CoveragePercent           float32                        `json:"coverage_percent"`
	TotalCells                uint32                         `json:"total_cells"`
	MowedCells                uint32                         `json:"mowed_cells"`
	ObstacleCells             uint32                         `json:"obstacle_cells"`
	StripsRemaining           uint32                         `json:"strips_remaining"`
}

// GetMowingAreaReq for mowgli_interfaces/srv/GetMowingArea request.
type GetMowingAreaReq struct {
	Index                     uint32                         `json:"index"`
}

// GetMowingAreaRes for mowgli_interfaces/srv/GetMowingArea response.
type GetMowingAreaRes struct {
	Area                      MapArea                        `json:"area"`
	Success                   bool                           `json:"success"`
}

// GetNextStripReq for mowgli_interfaces/srv/GetNextStrip request.
type GetNextStripReq struct {
	AreaIndex                 uint32                         `json:"area_index"`
	RobotX                    float64                        `json:"robot_x"`
	RobotY                    float64                        `json:"robot_y"`
	PreferHeadland            bool                           `json:"prefer_headland"`
}

// GetNextStripRes for mowgli_interfaces/srv/GetNextStrip response.
type GetNextStripRes struct {
	Success                   bool                           `json:"success"`
	CoverageComplete          bool                           `json:"coverage_complete"`
	StripPath                 nav.Path                       `json:"strip_path"`
	TransitGoal               geometry.PoseStamped           `json:"transit_goal"`
	CoveragePercent           float32                        `json:"coverage_percent"`
	StripsRemaining           uint32                         `json:"strips_remaining"`
	Phase                     string                         `json:"phase"`
}

// HighLevelControlReq for mowgli_interfaces/srv/HighLevelControl request.
type HighLevelControlReq struct {
	Command                   uint8                          `json:"command"`
}

// HighLevelControlRes for mowgli_interfaces/srv/HighLevelControl response.
type HighLevelControlRes struct {
	Success                   bool                           `json:"success"`
}

// MowerControlReq for mowgli_interfaces/srv/MowerControl request.
type MowerControlReq struct {
	MowEnabled                uint8                          `json:"mow_enabled"`
	MowDirection              uint8                          `json:"mow_direction"`
}

// MowerControlRes for mowgli_interfaces/srv/MowerControl response.
type MowerControlRes struct {
	Success                   bool                           `json:"success"`
}

// SetDockingPointReq for mowgli_interfaces/srv/SetDockingPoint request.
type SetDockingPointReq struct {
	DockingPose               geometry.Pose                  `json:"docking_pose"`
}

// SetDockingPointRes for mowgli_interfaces/srv/SetDockingPoint response.
type SetDockingPointRes struct {
	Success                   bool                           `json:"success"`
}

// TriggerReplanReq for mowgli_interfaces/srv/TriggerReplan request.
type TriggerReplanReq struct {
	Reason                    string                         `json:"reason"`
}

// TriggerReplanRes for mowgli_interfaces/srv/TriggerReplan response.
type TriggerReplanRes struct {
	Success                   bool                           `json:"success"`
	Message                   string                         `json:"message"`
}

